# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: shaoyin
middle_name: 
last_name: haung
email: 


lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 🐼 # the emoji used as the favicon
url: huangshaoyin.github.io #https://alshedivat.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
last_updated: true # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

